# Generated by Django 5.0.2 on 2024-10-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='registration',
            fields=[
                ('rollno', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('fname', models.CharField(max_length=225)),
                ('mname', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('program', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('regdate', models.DateTimeField()),
            ],
        ),
    ]
