# Generated by Django 5.0.2 on 2024-10-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0002_alter_registration_rollno'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=500)),
                ('contactno', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('enquirytext', models.CharField(max_length=500)),
                ('enqdate', models.DateTimeField()),
            ],
        ),
    ]
