# Generated by Django 5.0.2 on 2024-10-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0011_rename_feed_complaints_comp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='program',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='program',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
