# Generated by Django 5.0.2 on 2024-10-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='rollno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
