# Generated by Django 5.0.2 on 2024-10-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nouapp', '0007_upload_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
